# Generated by Django 3.0.7 on 2020-08-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200823_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='startingbid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(default=0.01, on_delete=django.db.models.deletion.CASCADE, related_name='total', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
