# Generated by Django 3.0.7 on 2020-08-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200826_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.ForeignKey(default=0.01, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Listing'),
        ),
    ]
