# Generated by Django 3.0.7 on 2020-08-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200830_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='user_id',
        ),
    ]
