# Generated by Django 3.0.7 on 2020-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200901_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currentbid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
