# Generated by Django 3.0.7 on 2020-09-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200902_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentbid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Current bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startbid',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=8, verbose_name='Starting bid'),
        ),
    ]
